// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmmyDNB5QV-s9Et3fVurf9Vt5HV5m-h2A',
    appId: '1:372906765429:web:a6e76303020130d904dc3c',
    messagingSenderId: '372906765429',
    projectId: 'login-68bb3',
    authDomain: 'login-68bb3.firebaseapp.com',
    storageBucket: 'login-68bb3.firebasestorage.app',
    measurementId: 'G-10VCX6P7R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAiQdgiyL8slTdA6hsbr_emz175I0UvE',
    appId: '1:372906765429:android:1b5b428034dead8f04dc3c',
    messagingSenderId: '372906765429',
    projectId: 'login-68bb3',
    storageBucket: 'login-68bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDbqs8wa1V9O99svLBgPo3LEhDGvpdVSs',
    appId: '1:372906765429:ios:6cdbd59626cf34ba04dc3c',
    messagingSenderId: '372906765429',
    projectId: 'login-68bb3',
    storageBucket: 'login-68bb3.firebasestorage.app',
    iosBundleId: 'com.example.appdiario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDbqs8wa1V9O99svLBgPo3LEhDGvpdVSs',
    appId: '1:372906765429:ios:6cdbd59626cf34ba04dc3c',
    messagingSenderId: '372906765429',
    projectId: 'login-68bb3',
    storageBucket: 'login-68bb3.firebasestorage.app',
    iosBundleId: 'com.example.appdiario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmmyDNB5QV-s9Et3fVurf9Vt5HV5m-h2A',
    appId: '1:372906765429:web:b99680935220d5bd04dc3c',
    messagingSenderId: '372906765429',
    projectId: 'login-68bb3',
    authDomain: 'login-68bb3.firebaseapp.com',
    storageBucket: 'login-68bb3.firebasestorage.app',
    measurementId: 'G-TEL213CJCS',
  );

}