// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-q9gALU8JYeR6guM5wBPxC5ACI6eXkuU',
    appId: '1:367849798274:web:f84066d42472acbccd129b',
    messagingSenderId: '367849798274',
    projectId: 'diariopessoal-a32d6',
    authDomain: 'diariopessoal-a32d6.firebaseapp.com',
    storageBucket: 'diariopessoal-a32d6.firebasestorage.app',
    measurementId: 'G-LK7WNDFQT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NdeCjxx4YJQPrwjcKvjOy-RNQsxNq3Y',
    appId: '1:367849798274:android:f7f29cce479a7af9cd129b',
    messagingSenderId: '367849798274',
    projectId: 'diariopessoal-a32d6',
    storageBucket: 'diariopessoal-a32d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9emY_n5ldCUgV6BaSOBgBF-faZMnPTGI',
    appId: '1:367849798274:ios:58e8d7519a424f58cd129b',
    messagingSenderId: '367849798274',
    projectId: 'diariopessoal-a32d6',
    storageBucket: 'diariopessoal-a32d6.firebasestorage.app',
    iosBundleId: 'com.example.appdiario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9emY_n5ldCUgV6BaSOBgBF-faZMnPTGI',
    appId: '1:367849798274:ios:58e8d7519a424f58cd129b',
    messagingSenderId: '367849798274',
    projectId: 'diariopessoal-a32d6',
    storageBucket: 'diariopessoal-a32d6.firebasestorage.app',
    iosBundleId: 'com.example.appdiario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-q9gALU8JYeR6guM5wBPxC5ACI6eXkuU',
    appId: '1:367849798274:web:33875666456600c9cd129b',
    messagingSenderId: '367849798274',
    projectId: 'diariopessoal-a32d6',
    authDomain: 'diariopessoal-a32d6.firebaseapp.com',
    storageBucket: 'diariopessoal-a32d6.firebasestorage.app',
    measurementId: 'G-GP5Z51KFBG',
  );
}
